package com.example.demo.mapper;


import com.example.demo.controller.dto.ItemDTO;
import com.example.demo.repository.model.Item;
import org.mapstruct.Mapper;

/**
 * Mapper with mapstruct, to map [ItemDTO] with [Item]
 * it is generated by maven
 */
@Mapper(componentModel = "spring")
public interface ItemMapper {
    ItemDTO itemToItemDTO(Item item);
    Item itemDTOToItem(ItemDTO itemDTO);
}
