package com.example.demo.mapper;

import com.example.demo.controller.dto.PersonDTO;
import com.example.demo.repository.model.Person;
import org.mapstruct.Mapper;

/**
 * Mapper with mapstruct, to map [PersonDTO] with [Person]
 * it is generated by maven
 */
@Mapper(componentModel = "spring")
public interface PersonMapper {
    PersonDTO personToPersonDTO(Person person);
    Person personDTOToPerson(PersonDTO personDTO);

}